import type { Employee } from "@/types/employee";

/**
 * Mock employee directory service. Replace the body of getEmployees with a
 * real API call once the Node.js backend exists — callers only depend on
 * this function's signature (Promise<Employee[]>).
 */

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: "EMP-1101",
    name: "Aarav Sharma",
    email: "aarav.sharma@hikeassociate.com",
    phone: "+91 98100 11234",
    designation: "Senior Software Engineer",
    level: "Senior",
    department: "Engineering",
    city: "Delhi",
    workLocationType: "Office",
    status: "Active",
    performanceScore: 87,
    skills: ["React", "TypeScript", "Node.js"],
    badges: ["Team Player", "Innovator"],
    joinedDate: "2022-03-14",
    manager: "Karan Malhotra",
  },
  {
    id: "EMP-1015",
    name: "Karan Malhotra",
    email: "karan.malhotra@hikeassociate.com",
    phone: "+91 98101 22345",
    designation: "Engineering Manager",
    level: "Manager",
    department: "Engineering",
    city: "Delhi",
    workLocationType: "Office",
    status: "Active",
    performanceScore: 94,
    skills: ["Leadership", "System Design", "Node.js"],
    badges: ["Leadership", "Mentor", "Star Performer"],
    joinedDate: "2019-06-02",
  },
  {
    id: "EMP-1204",
    name: "Meera Nair",
    email: "meera.nair@hikeassociate.com",
    phone: "+91 98102 33456",
    designation: "QA Engineer",
    level: "Associate",
    department: "Engineering",
    city: "Bangalore",
    workLocationType: "Hybrid",
    status: "Active",
    performanceScore: 78,
    skills: ["Automation Testing", "Selenium", "Cypress"],
    badges: ["Problem Solver"],
    joinedDate: "2023-01-09",
    manager: "Karan Malhotra",
  },
  {
    id: "EMP-1188",
    name: "Aditya Rao",
    email: "aditya.rao@hikeassociate.com",
    phone: "+91 98103 44567",
    designation: "Backend Engineer",
    level: "Associate",
    department: "Engineering",
    city: "Bangalore",
    workLocationType: "Office",
    status: "On Leave",
    performanceScore: 65,
    skills: ["Java", "Spring Boot", "PostgreSQL"],
    badges: [],
    joinedDate: "2023-08-21",
    manager: "Karan Malhotra",
  },
  {
    id: "EMP-1256",
    name: "Ishaan Gupta",
    email: "ishaan.gupta@hikeassociate.com",
    phone: "+91 98104 55678",
    designation: "Frontend Engineer",
    level: "Associate",
    department: "Engineering",
    city: "Pune",
    workLocationType: "Remote",
    status: "Remote",
    performanceScore: 91,
    skills: ["React", "Next.js", "Tailwind CSS"],
    badges: ["Innovator", "Go-Getter"],
    joinedDate: "2022-11-15",
    manager: "Karan Malhotra",
  },
  {
    id: "EMP-1301",
    name: "Tanvi Shah",
    email: "tanvi.shah@hikeassociate.com",
    phone: "+91 98105 66789",
    designation: "DevOps Engineer",
    level: "Senior",
    department: "Engineering",
    city: "Pune",
    workLocationType: "Hybrid",
    status: "Active",
    performanceScore: 83,
    skills: ["AWS", "Kubernetes", "Terraform"],
    badges: ["Problem Solver"],
    joinedDate: "2021-09-05",
    manager: "Karan Malhotra",
  },
  {
    id: "EMP-1340",
    name: "Yash Choudhary",
    email: "yash.choudhary@hikeassociate.com",
    phone: "+91 98106 77890",
    designation: "SDE Intern",
    level: "Intern",
    department: "Engineering",
    city: "Delhi",
    workLocationType: "Office",
    status: "Active",
    performanceScore: 58,
    skills: ["JavaScript", "Git"],
    badges: [],
    joinedDate: "2026-06-01",
    manager: "Karan Malhotra",
  },
  {
    id: "EMP-1120",
    name: "Diya Patel",
    email: "diya.patel@hikeassociate.com",
    phone: "+91 98107 88901",
    designation: "Product Designer",
    level: "Senior",
    department: "Engineering",
    city: "Mumbai",
    workLocationType: "Remote",
    status: "Remote",
    performanceScore: 94,
    skills: ["Figma", "Design Systems", "User Research"],
    badges: ["Innovator", "Star Performer"],
    joinedDate: "2021-02-18",
    manager: "Karan Malhotra",
  },
  {
    id: "EMP-1021",
    name: "Ananya Iyer",
    email: "ananya.iyer@hikeassociate.com",
    phone: "+91 98108 99012",
    designation: "HR Manager",
    level: "Manager",
    department: "HR",
    city: "Delhi",
    workLocationType: "Office",
    status: "Active",
    performanceScore: 92,
    skills: ["Talent Strategy", "Employee Relations", "HRIS"],
    badges: ["Leadership", "Helping Hand"],
    joinedDate: "2018-04-11",
  },
  {
    id: "EMP-1042",
    name: "Riya Kapoor",
    email: "riya.kapoor@hikeassociate.com",
    phone: "+91 98109 00123",
    designation: "HR Executive",
    level: "Executive",
    department: "HR",
    city: "Delhi",
    workLocationType: "Office",
    status: "Active",
    performanceScore: 74,
    skills: ["Onboarding", "Payroll Support", "Compliance"],
    badges: ["Helping Hand"],
    joinedDate: "2023-05-22",
    manager: "Ananya Iyer",
  },
  {
    id: "EMP-1033",
    name: "Simran Kaur",
    email: "simran.kaur@hikeassociate.com",
    phone: "+91 98110 11234",
    designation: "Talent Acquisition Specialist",
    level: "Executive",
    department: "HR",
    city: "Gurgaon",
    workLocationType: "Hybrid",
    status: "Active",
    performanceScore: 88,
    skills: ["Sourcing", "Interviewing", "ATS"],
    badges: ["Go-Getter"],
    joinedDate: "2022-07-19",
    manager: "Ananya Iyer",
  },
  {
    id: "EMP-1358",
    name: "Pooja Iyer",
    email: "pooja.iyer@hikeassociate.com",
    phone: "+91 98111 22345",
    designation: "HR Associate",
    level: "Associate",
    department: "HR",
    city: "Delhi",
    workLocationType: "Office",
    status: "Active",
    performanceScore: 70,
    skills: ["Documentation", "Employee Engagement"],
    badges: [],
    joinedDate: "2024-02-12",
    manager: "Ananya Iyer",
  },
  {
    id: "EMP-1027",
    name: "Rohan Desai",
    email: "rohan.desai@hikeassociate.com",
    phone: "+91 98112 33456",
    designation: "Payroll Manager",
    level: "Manager",
    department: "Finance",
    city: "Mumbai",
    workLocationType: "Office",
    status: "On Leave",
    performanceScore: 85,
    skills: ["Payroll", "Compliance", "Excel"],
    badges: ["Team Player"],
    joinedDate: "2020-01-27",
  },
  {
    id: "EMP-1372",
    name: "Manish Agarwal",
    email: "manish.agarwal@hikeassociate.com",
    phone: "+91 98113 44567",
    designation: "Financial Analyst",
    level: "Associate",
    department: "Finance",
    city: "Mumbai",
    workLocationType: "Office",
    status: "Active",
    performanceScore: 62,
    skills: ["Financial Modeling", "Excel", "Budgeting"],
    badges: [],
    joinedDate: "2023-10-03",
    manager: "Rohan Desai",
  },
  {
    id: "EMP-1389",
    name: "Sneha Kulkarni",
    email: "sneha.kulkarni@hikeassociate.com",
    phone: "+91 98114 55678",
    designation: "Accounts Executive",
    level: "Executive",
    department: "Finance",
    city: "Pune",
    workLocationType: "Hybrid",
    status: "Active",
    performanceScore: 90,
    skills: ["Bookkeeping", "Tax Filing", "Reconciliation"],
    badges: ["Star Performer"],
    joinedDate: "2021-12-06",
    manager: "Rohan Desai",
  },
  {
    id: "EMP-1401",
    name: "Devika Pillai",
    email: "devika.pillai@hikeassociate.com",
    phone: "+91 98115 66789",
    designation: "Finance Intern",
    level: "Intern",
    department: "Finance",
    city: "Mumbai",
    workLocationType: "Office",
    status: "Active",
    performanceScore: 55,
    skills: ["Excel", "Data Entry"],
    badges: [],
    joinedDate: "2026-07-01",
    manager: "Rohan Desai",
  },
  {
    id: "EMP-1410",
    name: "Priya Menon",
    email: "priya.menon@hikeassociate.com",
    phone: "+91 98116 77890",
    designation: "Marketing Lead",
    level: "Manager",
    department: "Marketing",
    city: "Bangalore",
    workLocationType: "Hybrid",
    status: "Active",
    performanceScore: 96,
    skills: ["Brand Strategy", "Campaign Management", "Analytics"],
    badges: ["Star Performer", "Innovator", "Leadership"],
    joinedDate: "2019-11-25",
  },
  {
    id: "EMP-1418",
    name: "Anika Bose",
    email: "anika.bose@hikeassociate.com",
    phone: "+91 98117 88901",
    designation: "Content Strategist",
    level: "Associate",
    department: "Marketing",
    city: "Bangalore",
    workLocationType: "Remote",
    status: "Remote",
    performanceScore: 80,
    skills: ["Content Strategy", "SEO", "Copywriting"],
    badges: ["Team Player"],
    joinedDate: "2022-09-14",
    manager: "Priya Menon",
  },
  {
    id: "EMP-1425",
    name: "Varun Kapoor",
    email: "varun.kapoor@hikeassociate.com",
    phone: "+91 98118 99012",
    designation: "SEO Executive",
    level: "Executive",
    department: "Marketing",
    city: "Chennai",
    workLocationType: "Office",
    status: "Active",
    performanceScore: 68,
    skills: ["SEO", "Google Analytics", "Content Marketing"],
    badges: [],
    joinedDate: "2023-06-30",
    manager: "Priya Menon",
  },
  {
    id: "EMP-1430",
    name: "Siddharth Rao",
    email: "siddharth.rao@hikeassociate.com",
    phone: "+91 98119 00123",
    designation: "Sales Manager",
    level: "Manager",
    department: "Sales",
    city: "Mumbai",
    workLocationType: "Office",
    status: "Active",
    performanceScore: 89,
    skills: ["B2B Sales", "Negotiation", "CRM"],
    badges: ["Go-Getter", "Customer Champion"],
    joinedDate: "2020-08-17",
  },
  {
    id: "EMP-1438",
    name: "Nikita Malhotra",
    email: "nikita.malhotra@hikeassociate.com",
    phone: "+91 98120 11234",
    designation: "Account Executive",
    level: "Executive",
    department: "Sales",
    city: "Mumbai",
    workLocationType: "Hybrid",
    status: "Active",
    performanceScore: 72,
    skills: ["Client Relations", "CRM", "Upselling"],
    badges: ["Customer Champion"],
    joinedDate: "2023-03-27",
    manager: "Siddharth Rao",
  },
  {
    id: "EMP-1445",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@hikeassociate.com",
    phone: "+91 98121 22345",
    designation: "Business Development Associate",
    level: "Associate",
    department: "Sales",
    city: "Chennai",
    workLocationType: "Office",
    status: "Inactive",
    performanceScore: 60,
    skills: ["Lead Generation", "Cold Calling"],
    badges: [],
    joinedDate: "2022-05-09",
    manager: "Siddharth Rao",
  },
  {
    id: "EMP-1450",
    name: "Kabir Singh",
    email: "kabir.singh@hikeassociate.com",
    phone: "+91 98122 33456",
    designation: "Operations Manager",
    level: "Manager",
    department: "Operations",
    city: "Delhi",
    workLocationType: "Office",
    status: "Active",
    performanceScore: 93,
    skills: ["Process Optimization", "Vendor Management", "Logistics"],
    badges: ["Leadership", "Problem Solver"],
    joinedDate: "2019-02-04",
  },
  {
    id: "EMP-1458",
    name: "Neha Joshi",
    email: "neha.joshi@hikeassociate.com",
    phone: "+91 98123 44567",
    designation: "Admin Executive",
    level: "Executive",
    department: "Operations",
    city: "Delhi",
    workLocationType: "Office",
    status: "Active",
    performanceScore: 76,
    skills: ["Facility Management", "Vendor Coordination"],
    badges: ["Helping Hand"],
    joinedDate: "2022-10-11",
    manager: "Kabir Singh",
  },
  {
    id: "EMP-1465",
    name: "Arjun Nair",
    email: "arjun.nair@hikeassociate.com",
    phone: "+91 98124 55678",
    designation: "Operations Associate",
    level: "Associate",
    department: "Operations",
    city: "Bangalore",
    workLocationType: "Office",
    status: "Active",
    performanceScore: 52,
    skills: ["Inventory Management", "MS Excel"],
    badges: [],
    joinedDate: "2024-01-15",
    manager: "Kabir Singh",
  },
];

function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export async function getEmployees(): Promise<Employee[]> {
  await delay(250);
  return MOCK_EMPLOYEES;
}

export function getEmployeeById(id: string): Employee | undefined {
  return MOCK_EMPLOYEES.find((employee) => employee.id === id);
}
